---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r}
#Checking to see if Zipped file exists
if(file.exists("activity.zip")){
        unzip("activity.zip", overwrite=TRUE)
}

#reading data
activitydata<-read.csv("activity.csv",header=TRUE)

```


## What is mean total number of steps taken per day?

### Used aggregate function to get the mean/median of the steps/day based on date
### Aggregate function ignores the NA values by default

```{r}

stepsPerDay<-aggregate(steps ~ date, data=activitydata,sum)

#Trying to plot
hist(stepsPerDay$steps,xlab="Sum of Steps", main="Total number of steps each day")

#mean of steps/day
print(aggregate(steps ~ date, data=activitydata,mean))

#median of steps/day
print(median(stepsPerDay$steps))

```

## What is the average daily activity pattern?


```{r}

#mean of steps per time interval
#print(aggregate(steps ~ interval, data=activitydata,mean))
stepsInterval<-aggregate(steps ~ interval, data=activitydata,mean)

#Getting the time series
timeSeries <- ts(stepsInterval$steps)

plot(timeSeries, type="l", xlab="Interval", ylab="Average per Interval",main="Average Steps per Time interval")

```

## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
